name: Remote Trigger

on: repository_dispatch

jobs:
  run:
    name: Dispatch Event
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh

    - name: Handle Event
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        GIT_AUTHOR_EMAIL: ${{ secrets.PUSH_EMAIL }}
        GIT_COMMITTER_EMAIL: ${{ secrets.PUSH_EMAIL }}
      run: bash ./tools/repository_dispatch.sh

    - name: Upload build
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: build
        path: build

    - name: Upload archive
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: artifacts
        path: dist
